TARGET_2 = queue-threads
SRCS_2 = queue.c queue-threads.c

CC=gcc
RM=rm
CFLAGS = -Wall -Wextra -pedantic -g
LIBS=-lpthread
INCLUDE_DIR="."

${TARGET_2}: queue.h ${SRCS_2}
	${CC} ${CFLAGS} -I${INCLUDE_DIR} ${SRCS_2} ${LIBS} -o ${TARGET_2}

clean:
	${RM} -f *.o ${TARGET_1} ${TARGET_2}
